# Generated by Django 5.1.2 on 2025-01-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_mongouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MongoUser',
        ),
    ]
