# Generated by Django 5.1.2 on 2025-01-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_userprofile_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
